// Code generated by "stringer -type=Keyword"; DO NOT EDIT.

package keyword

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[UNDEFINED-0]
	_ = x[BeginArray-1]
	_ = x[BeginObject-2]
	_ = x[EndArray-3]
	_ = x[EndObject-4]
	_ = x[NameSeparator-5]
	_ = x[ValueSeparator-6]
	_ = x[LiteralFalse-7]
	_ = x[LiteralNull-8]
	_ = x[LiteralTrue-9]
	_ = x[Quote-10]
	_ = x[String-11]
	_ = x[Number-12]
	_ = x[Minus-13]
	_ = x[Plus-14]
	_ = x[EOF-15]
}

const _Keyword_name = "UNDEFINEDBeginArrayBeginObjectEndArrayEndObjectNameSeparatorValueSeparatorLiteralFalseLiteralNullLiteralTrueQuoteStringNumberMinusPlusEOF"

var _Keyword_index = [...]uint8{0, 9, 19, 30, 38, 47, 60, 74, 86, 97, 108, 113, 119, 125, 130, 134, 137}

func (i Keyword) String() string {
	if i < 0 || i >= Keyword(len(_Keyword_index)-1) {
		return "Keyword(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Keyword_name[_Keyword_index[i]:_Keyword_index[i+1]]
}
